package com.cst438.dto;

import jakarta.validation.constraints.*;

// on registration, name, email, password are validated.  customerId, name, email are returned.
// on login return value of customerDTO contains customerId, name, email and jwtToken.
public record CustomerDTO(
        // value generated by database
        int customerId,
        @NotBlank(message = "Name can not be empty")
        @NotNull(message = "User must have name")
        @Pattern(regexp = "[a-zA-Z]*", message = "Name can only have letters")
        String name,
        @Email(message = "Email is not valid")
        @NotBlank(message = "Email can not be empty")
        @NotNull(message = "User must have Email")
        String email,
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$", message = "Password can only contain letters, numbers, underscores, and hyphens")
        String password,  // used for registration
        String jwtToken) {
}
