package com.cst438.dto;

import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.sql.Date;

public record OrderDTO (
        // value generated by database
        int orderId,

        // value set by controller
        Date orderDate,
        @NotNull(message="Item can not be null")
        @Size(min = 2, max = 20, message = "Item must be between 2 and 20 characters")
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$", message = "Item can only contain letters, numbers, underscores, and hyphens")
        String item,
        @Positive(message="Order quantity must be greater than 0")
        @Max(value = 100, message = "Order quantity must be less or equal 100")
        int quantity,
        @Digits(integer = 3, fraction = 2, message = "Invalid price")
        @Positive(message="Price must be greater than 0")
        BigDecimal price
        ) {
}

