package com.cst438.dto;

import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.sql.Date;

public record OrderDTO (
        int orderId,     // value generated by database
        Date orderDate,  // value set by controller
        @Pattern(regexp ="^[a-zA-Z0-9-]+$", message="bad item")
        @NotNull(message="item can not be null")
        String item,
        @Positive(message="quantity must be positive")
        @Max(value=100, message="quantity must be less equal to 100")
        int quantity,
        @Digits(integer = 3, fraction = 2, message = "invalid price")
        @Positive(message="price must be greater than 0")
        BigDecimal price ) {
}

