package com.cst438.domain;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.sql.Date;

//  mark this class as entity with annotation
@Entity
//  the table is "ordertab", not order so we need a @Table annotation
//  @Table(name="ordertab")
public class Order {
    // orderId is primary key
    @Id
    // the value is generated by the database so use  @GeneratedValue(strategy= GenerationType.IDENTITY)
    private int orderId;
    private Date orderDate;
    private String item;
    private int quantity;
    private BigDecimal price;

    // Declare a many-to-one relationship, a customer has many orders,
    // each order to related to one customer  using @ManyToOne
    // the relationship is mapped to the foreign key column "cust_id"  @JoinColumn(name="cust_id", nullable=false)
    private Customer customer;

    // generate get/set methods for all fields
}
