package com.cst438.dto;

    public record CustomerLoginDTO(
            int customerId,     // value generated by database
            String name,
            String token // returned from login
    ) {
    }

