package com.cst438.dto;


import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Pattern;

public record CustomerDTO(
        int customerId,     // value generated by database
        @Pattern(regexp ="^[a-zA-Z ]+$", message="bad name")
        String name,
        @Email(message="bad email")
        String email,
        @Pattern(regexp ="^[a-zA-Z0-9$]+$", message="bad password")
        String password,    // used for registration
        String jwtToken ) { // returned from login
}
