package com.cst438.dto;


public record CustomerDTO(
        int customerId,     // value generated by database
        String name,
        String email,
        String password,    // used for registration
        String jwtToken ) { // returned from login
}
