package com.cst438.dto;

import java.math.BigDecimal;
import java.sql.Date;

public record OrderDTO (
        int orderId,     // value generated by database
        Date orderDate,  // value set by controller
        String item,
        int quantity,
        BigDecimal price ) {
}

