package com.cst438.domain;

import jakarta.persistence.*;

import java.util.List;

//  mark this class as entity with annotation
@Entity
public class Customer {
    // define the primary key of customerId that maps to the cust_id column in the database table
    @Id
    // the value for customerId is generated by the database
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="cust_id")
    private int customerId;
    private String name;
    private String email;
    private String password;

    // Define a one-to-many relationship.  a customer can have many orders
    // the orders are listed in reverse chronological sequence, the most recent order first.
    @OneToMany(mappedBy="customer")
    @OrderBy("orderDate desc, orderId desc")
    private List<Order> orders;

    // add get/set methods for all attributes

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }
}
